name: Release

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'  # 指定 JDK 的分发版本
          java-version: '21'

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Upload JAR to GitHub Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./target/BasicSpringBoot.jar  # 更新后的文件路径
          asset_name: BasicSpringBoot.jar           # 上传到 Release 的文件名
          asset_content_type: application/java-archive

